[project]
name = "manuscript2slides"
version = "0.0.0"
requires-python = ">=3.10"
description = "Convert Word documents to PowerPoint slides"
dependencies = [
    "python-docx",
    "python-pptx",
    "platformdirs>=3.5",
    "tomli>=2.0.0; python_version < '3.11'",  # Only install if Python < 3.11
    "tomli-w>=1.0.0",
]
[project.optional-dependencies]
dev = [
    "tomli>=2.0.0",  # Always install for dev, even on 3.11+
    "tomli-w>=1.0.0",
]
authors = [{name = "talosgl"}]

# Convention is: [project] -> [tool.*] sections -> [build-system] last.

[tool.setuptools.package-data]
manuscript2slides = [
    "resources/*.pptx",
    "resources/*.docx",
    "resources/*.md",
    "resources/*.yaml"
]

[tool.ruff]
lint.select = ["D100", "D101", "D102", "D103", "ANN"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"