[project]
name = "docx2pptx_text"
version = "0.0.0"
requires-python = ">=3.10"
description = "Convert Word documents to PowerPoint slides"
dependencies = [
    "python-docx",
    "python-pptx",
    "PyYAML"
]
authors = [{name = "talosgl"}]

[tool.ruff]
lint.select = ["D100", "D101", "D102", "D103", "ANN"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"